### PR TITLE
Some little improvements

### PR DESCRIPTION
**Pull request by danigb**
- Update soundfont-player to remove missing instruments exceptions (look at the new https://github.com/danigb/soundfont-player/blob/master/musyngkite.json names file)
- Use npm to download initial dependencies (and avoid pollute the global npm space) and run build scripts

### CODE REVIEW

**Comment by newlandsvalley** [comment]
Very many thanks, Dani!  I'll merge this later on this afternoon.

**Comment by newlandsvalley** [comment]
Do I need yarn.lock - I'd not heard of Yarn before?  I noticed the hint when running npm install that Yarn is preferred over Bower.  Purescript tends to recommend Bower although a psc-package will eventually be the way to go.

**Comment by danigb** [comment]
`yarn` is a new javascript tool that's becoming very popular (as an alternative of npm) and having yarn.lock helps to provide support to it (yarn uses yarn.lock to install dependencies faster). I can remove it if you prefer (and stick with npm).

I will try to clean your javascript a bit this evening... aside from that, everything seems to work perfectly, congrats! Is anything else do you want me to try in your code base?

**Comment by newlandsvalley** [comment]
OK - I'll keep it and try to learn a bit about Yarn.  Many thanks for the review and the offer to clean up the javascript!

**Pull request merged**
